redis:
  addr: "localhost:6379"

db:
  #    mysql-local
  dsn: "root:aaa@tcp(localhost:3306)/denttick"

regexp:
  passwordRegex: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,72}$"
  phoneRegex: "^1[3-9]\\d{9}$"

log: